baseURL = "https://rishabh1403.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cactus-plus"


# Theme settings start may contain settings that i may use for other themes in future
[params]
author = "site_author"
description = "Site Description"
bio = "author biography"

twitter = "your_twitter_id"
facebook = "your_facebook_id"

enableRSS = true
enableToc = true

enableDisqus = true
disqusShortname = "your_disqus_short_name"


enableSummary = true
# Set the value to true if use description in post front matter replace content summary
useDescriptionReplaceSummary = false


enableGoogleAnalytics = true

enableTwitterCard = true
# The url for twitter card image, default is avatar.png in static/images directory
twitterCardImage = ""

# Add custom assets with their paths relative to the static folder
customCSS = []
customJS  = []

# The variables below are optionally too and can be used to
# translate or customize each string of the theme.

# Navigation links
home = ""
about = ""
archive = ""
subscribe = ""

olderPosts = ""
newerPosts = ""
copyright = ""

# show latest posts in single page
showLatestPosts = false
readMore = ""

# Share
enableShare = true
tweet = ""
share = ""

# 404 page
title404 = "Stuart Not Found"
subtitle404 = "Not Found Baba"

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "font-awesome"
# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
socialIconStyle = ""


# Add additional social link entries underneath

[social]
facebook-square = "https://www.facebook.com/nodejh"
twitter-square = "https://www.twitter.com/nodejh"
github-square = "https://www.github.com/nodejh"
