baseURL = "https://rishabh1403.com/"
languageCode = "en-us"
title = "Rishabh Jain"
theme = "cactus-plus"

googleAnalytics = "UA-66600089-2"

# Theme settings start may contain settings that i may use for other themes in future
[params]
author = "Rishabh Jain"
description = "Rishabh's Blog"
bio = "Full Stack Developer"

twitter = "rishabhjain1403"
facebook = "rishabhjain1403"

enableRSS = true
enableToc = true

enableDisqus = true
disqusShortname = "rishabh1403-1"


enableSummary = true
# Set the value to true if use description in post front matter replace content summary
useDescriptionReplaceSummary = true


enableGoogleAnalytics = true

enableTwitterCard = true
# The url for twitter card image, default is avatar.png in static/images directory
twitterCardImage = ""

# Add custom assets with their paths relative to the static folder
customCSS = []
customJS  = []

# The variables below are optionally too and can be used to
# translate or customize each string of the theme.

# Navigation links
home = ""
about = ""
archive = ""
tags= ""
categories=""
subscribe = ""

olderPosts = ""
newerPosts = ""
copyright = ""

# show latest posts in single page
showLatestPosts = false
readMore = ""

# Share
enableShare = true
tweet = ""
share = ""

# 404 page
title404 = "Stuart Not Found"
subtitle404 = "Not Found"

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "font-awesome"
# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
socialIconStyle = ""


# Add additional social link entries underneath

[social]
#facebook-square = "https://www.facebook.com/nodejh"
envelope-square = "mailto:contact@rishabh1403.com"
twitter-square = "https://www.twitter.com/rishabhjain1403"
github-square = "https://www.github.com/rishabh1403"
